# Generated by Django 5.2 on 2025-04-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=35)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=25)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
