# Generated by Django 5.2 on 2025-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='username',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
