# Generated by Django 5.2 on 2025-04-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0002_jobseeker_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='username',
        ),
    ]
