# Generated by Django 5.2 on 2025-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0002_remove_employee_website_remove_jobseeker_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('discription', models.TextField()),
                ('requirements', models.TextField()),
                ('salary_range', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=250)),
                ('application_deadline', models.DateField()),
            ],
        ),
    ]
