# Generated by Django 5.2 on 2025-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0005_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seekers_resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
