# Generated by Django 5.2 on 2025-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0008_job_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='dp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
