# Generated by Django 5.2 on 2025-04-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0010_emailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='message',
            field=models.CharField(default=1, max_length=25000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='subject',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
