# Generated by Django 5.2 on 2025-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0011_emailrecord_message_emailrecord_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='message',
            field=models.CharField(default='Default message', max_length=25000),
        ),
    ]
